Implement cron deployment in production + add names to both scripts

diff --git a/.github/workflows/deploy-prod.yaml b/.github/workflows/deploy-prod.yaml
--- a/.github/workflows/deploy-prod.yaml
+++ b/.github/workflows/deploy-prod.yaml
@@ -1,3 +1,6 @@
+name: deploy-prod
+run-name: Deploying to production on ${{ github.actor }}'s commits
+
 on:
   push:
     # branches:
@@ -8,9 +11,10 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  buildImage:
-    name: Build Image & Deploy to Docker Hub
+  buildCronImage:
+    name: Build Cron Image & Deploy to Docker Hub
     runs-on: ubuntu-latest
+    environment: staging
 
     steps:
       - name: Checkout Repository
@@ -19,14 +23,16 @@ jobs:
       - name: Run script
         run: bash .github/scripts/build-image.sh
         env:
+          DOCKER_HUB_PAT: ${{ secrets.DOCKER_HUB_PAT }}
           TYPE: cron
           DOCKER_UPLOAD: true
-          DOCKER_HUB_PAT: ${{ secrets.DOCKER_HUB_PAT }}
+          DOCKER_FILE_NAME: Dockerfile.scripts
 
-  redeploy:
-    name: Redeploy on Coolify
+  redeployCron:
+    name: Redeploy Cron on Coolify
+    needs: buildCronImage
     runs-on: ubuntu-latest
-    enviornment: staging
+    environment: production
 
     steps:
       - name: Checkout Repository
@@ -36,9 +42,9 @@ jobs:
         run: |
           RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" \
           -X POST \
-          -H "Authorization: Bearer ${{ secrets.DIGITAL_OCEAN_PAT }}" \
+          -H "Authorization: Bearer ${{ secrets.COOLIFY_PAT }}" \
           -H "Content-Type: application/json" \
-          https://coolify.tahmid.io/v1/deploy?uuid=${{ secrets.COOLIFY_UUID }}/deployments)
+          https://coolify.tahmid.io/api/v1/deploy?uuid=${{ secrets.COOLIFY_CRON_UUID }})
 
           HTTP_BODY=$(echo "$RESPONSE" | sed -e 's/HTTPSTATUS:.*//g')
           HTTP_STATUS=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
@@ -49,6 +55,42 @@ jobs:
               exit 1
           fi
 
-          DEPLOYMENT_ID=$(echo "$HTTP_BODY" | jq -r '.deployment.id')
+          DEPLOYMENT_ID=$(echo "$HTTP_BODY" | jq -r '.deployments[0].deployment_uuid')
 
           echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_ENV
+
+      - name: Poll Deployment Status
+        run: |
+          DEPLOYMENT_ID="$deployment_id"
+
+           if [ -z "$DEPLOYMENT_ID" ]; then
+               echo "Deployment ID is empty."
+               exit 1
+           fi
+
+          echo "Waiting for deployment to be promoted."
+
+          for i in {1..60}; do
+              RESPONSE=$(curl -s -X GET \
+                  -H "Content-Type: application/json" \
+                  -H "Authorization: Bearer ${{ secrets.COOLIFY_PAT }}" \
+                  "https://coolify.tahmid.io/api/v1/deployments/$DEPLOYMENT_ID")
+
+              PHASE=$(echo "$RESPONSE" | jq -r '.status')
+
+              echo "Deployment phase: $PHASE"
+
+              if [ "$PHASE" == "finished" ]; then
+                  echo "Deployment is active."
+                  exit 0
+              elif [ "$PHASE" == "failed" ] || [ "$PHASE" == "error" ] || [ "$PHASE" == "canceled" ]; then
+                  echo "Deployment failed with phase: $PHASE"
+                  exit 1
+              fi
+
+              echo "Waiting for deployment to complete, sleep 10... ($i/60)"
+              sleep 10
+          done
+
+          echo "Deployment did not reach a valid state within 10 minutes."
+          exit 1
